### ISSUE TITLE
"Failed to Setup" when adding ttlock to Home Assistant 

### ISSUE THREAD

**Issue by blakejake33** [jbergler/hass-ttlock#86]
Once the TTlock information is input into Home Assitant, it says "Failed to Setup" and I never get the  webhook url notification.

1st) I set up an account at https://euopen.ttlock.com/login and submitted an application and was approved.
2nd) I then added the client_id and client_secret to home Assitant 
3rd) I enter my login info for TTlock 

And this is as far as im able to go before the "failed to set up" appears. 

Ive tried changing my ttlock password, re-adding the lock to the app, reinstalling the ttlock addon. 

Ive attatched my log
[error_log-2.txt](https://github.com/jbergler/hass-ttlock/files/13775480/error_log-2.txt)

**Comment by jbergler** [comment]
Hello, thanks for the bug report and including the logs.

Looks like the issue here might be that your home assistant instance hasn't been configured with a URL somehow.
Could you go to "Settings > System > Network" and check what value are set in the "Home Assistant URL" section? A screenshot would be great if there's no sensitive info in there.

This will help me confirm my fix is the right one.

**Comment by blakejake33** [comment]
THANK YOU! that was it! I added my HA Url and now the device shows! ![Screenshot_20231227_190006_Home Assistant.jpg](https://github.com/jbergler/hass-ttlock/assets/71988323/13462f60-3e16-4bb8-8b18-06b9660c2ffc)
